---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-trivia-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-trivia-app
  template:
    metadata:
      labels:
        name: go-trivia-app
    spec:
      containers:
      - name: trivia-backend
        image: csheehy/imagers:trivia
        imagePullPolicy: Always
        ports:
          - containerPort: 3000