---
apiVersion: v1
kind: Service
metadata:
  name: go-trivia-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: go-trivia-app